//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace climate_API.Models.entityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class climateEntities : DbContext
    {
        public climateEntities()
            : base("name=climateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAlert> tblAlert { get; set; }
        public virtual DbSet<tblClimaticPhenomenon> tblClimaticPhenomenon { get; set; }
        public virtual DbSet<tblCountry> tblCountry { get; set; }
        public virtual DbSet<tblTerritory> tblTerritory { get; set; }
        public virtual DbSet<tblTypeTemperature> tblTypeTemperature { get; set; }
        public virtual DbSet<tblUsers> tblUsers { get; set; }
        public virtual DbSet<tblWeatherForecast> tblWeatherForecast { get; set; }
        public virtual DbSet<tblWeatherStation> tblWeatherStation { get; set; }
    }
}
