//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace climate_API.Models.entityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTerritory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTerritory()
        {
            this.tblWeatherStation = new HashSet<tblWeatherStation>();
        }
    
        public int ID { get; set; }
        public string NameTerritory { get; set; }
        public int Id_Country { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblWeatherStation> tblWeatherStation { get; set; }
    }
}
