//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace climate_API.Models.entityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWeatherForecast
    {
        public long ID { get; set; }
        public string ClimaticDescription { get; set; }
        public System.DateTime DateRegister { get; set; }
        public decimal Temperature { get; set; }
        public int IdTypeTemperature { get; set; }
        public Nullable<int> IdClimaticPhenomenon { get; set; }
        public Nullable<int> IdAlert { get; set; }
        public int IdWeatherStation { get; set; }
        public int StateRegister { get; set; }
    
        public virtual tblAlert tblAlert { get; set; }
        public virtual tblClimaticPhenomenon tblClimaticPhenomenon { get; set; }
        public virtual tblTypeTemperature tblTypeTemperature { get; set; }
        public virtual tblWeatherStation tblWeatherStation { get; set; }
    }
}
